version: 2

sources:
  - name: customers_raw
    schema: staging
    description: customers raw data

    tables:
      - name: customers
      

models:
  - name: customers
    description: this table contains Males top 50 income
  - name: profess_income
    description: this table contains every aggregated income by profession
    config:
      materialized: table

  - name: customers
    description: "The final customer dimension table."
    columns:
      # We define the simple tests directly on the column
      - name: customer_id
        description: "The unique identifier for the customer."
        tests:
          - unique
          - not_null
      
      # Add your other columns here without any tests yet
      - name: gender
      - name: age
      # ... other columns ...